-- Pins table seeds here
INSERT INTO pins (map_id, user_id, title, description, image_url, longitude, latitude)
VALUES

-- BC
(1, 1, 'Sunshine Coast Trail', 'Located in the Powell River area, Canadas longest hut-to-hut hiking trail. It stretches over 180km that range from coastal shorelines and old growth forests to pristine lakes and panoramic mountaintops.', 'https://images.pexels.com/photos/287240/pexels-photo-287240.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&dpr=1', '-124.1367', '49.8114'),

(1, 1, 'Al Habrichs Ridge Trail', 'Taking around 5-6 hours to hike, as the walk leads you out near the majestic Neverland Lake The route goes just beyond Neverland Lake and an extended route can be hiked to Neverland Falls. The Als Habrich Ridge Trail is best done by taking the Sea To Sky gondola to the top but can also be done after hiking the Sea To Summit route from the bottom of the gondola.', 'https://images.pexels.com/photos/56760/pexels-photo-56760.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&dpr=1', '-123.115239', '49.676976'),

(1, 1, 'Black Tusk Trail', 'The dark, jagged edges of Black Tusk make it one of the most scenic and unique hikes in southwestern British Columbia. Black Tusk is the most spectacular mountain in the area, and one of the most difficult terrain, with 29 km round trip. and elevation gain of 1740 meters. ', 'https://images.pexels.com/photos/868097/pexels-photo-868097.jpeg?auto=compress&cs=tinysrgb&w=500&h=500&dpr=1', '-123.042753', '49.9751162'),

(1, 1, 'Elfin Lakes', 'Two lakes in Garibaldi Provincial Park that are popular for hiking, snowshoeing, skiing, and mountain bicycling trail located east of Squamish, British Columbia, Canada.', 'https://upload.wikimedia.org/wikipedia/commons/1/1c/ElfinPano.jpg', '-122.4762', '50.3413'),

(1, 1, 'Joffre Lakes', 'A provincial park located 35 kilometres (22 mi) east of Pemberton in British Columbia, Canada. It was established in 1996, when Joffre Lakes Recreation Area (created 1988) was upgraded to park status. Three glacier-fed lakes are located in the park: Lower, Middle, and Upper Joffre Lakes. The rock flour in the water reflects blue and green waves, and gives the lakes a turquoise colour. Joffre Lakes is a popular destination for hikers in the summer and mountain climbers in the winter due to its scenic lakes, glaciers and challenging peaks.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Upper_Joffre_Lake_-_British_Columbia%2C_Canada.jpg/1920px-Upper_Joffre_Lake_-_British_Columbia%2C_Canada.jpg', '-122.98824611814419', '49.787158149999996'),

-- VC
(2, 1, 'The Mexican Antojitos y Cantina', 'The Mexican, antojitos y cantina offers many fine traditional Mexican dishes with the real taste from México!
So if you are craving for Traditional Mexican menu items such as Quesadillas, Grilled Meats, Real Tacos, Guacamole and a great Drinks menu, what are you waiting for ?
We are located in the heart of downtown Vancouver  on Granville Street.', 'https://images.pexels.com/photos/7772198/pexels-photo-7772198.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '-123.124006', '49.278797'),

(2, 1, 'La Taqueria Pinche Taco Shop', 'All our dishes are made from traditional recipes using local, organic and sustainable products when possible. From our classic tacos, quesadillas and burritos to our new additions; we express a little bit of Mexico, their history and unique flavours in every dish. La Taqueria food is vibrant, delicious, fresh and fun.', 'https://images.pexels.com/photos/2092897/pexels-photo-2092897.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '-123.112674', '49.263558'),

(2, 1, 'Mi Casa Mexicana', 'Home made style mexican food', 'https://images.squarespace-cdn.com/content/v1/5c35239c697a982d0e21bcc2/1621570365263-WHCXQ895T0NOXCLUO8NT/IMG_8955.JPG?format=500w', '-123.1458856', '49.2678006'),

(2, 1, 'Chancho Tortilleria', 'In Mexico, at the heart of every community is the tortilleria. Chancho brings that authentic, small-town feeling to Vancouvers Yaletown neighbourhood.', 'https://images.pexels.com/photos/7613562/pexels-photo-7613562.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '-123.124905', '49.2761708'),

(2, 1, 'La Mezcaleria', 'Latin American small plates, creative entrees & cocktails in arty, industrial-chic surrounds.', 'https://images.pexels.com/photos/4958730/pexels-photo-4958730.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '-123.0694291', '49.2701295'),

-- AB
(3, 1, 'Town of Banff', 'Located in the south end of Banff National Park, this little town, surrounded by mountains, is one of the main tourist destinations in Alberta. It is devoted to the tourism industry with all kinds of accommodation options, interesting shops, and restaurants that range from casual to high end.', 'https://www.planetware.com/photos-large/CDN/canada-banff-town-street.jpg', '-115.5682504', '51.1777781'),

(3, 1, 'Lake Louise', 'its shimmering turquoise green water and surrounding snow-capped mountains rising up to 3,000 meters high. Although the water is too cold for swimming, it is ideal for canoeing. At the western end of Lake Louise, Mount Victoria (3,469 meters), rises in majestic splendor.', 'https://www.planetware.com/photos-large/CDN/canada-banff-lake-louise-canoes.jpg', '-116.22896211178153', '51.4114544'),

(3, 1, 'Icefields Parkway', 'The Icefields Parkway runs from Lake Louise to Jasper and is one of the most beautiful drives in Canada. This 230-kilometer stretch of highway leads past lakes, mountains, glaciers, and waterfalls, with stopping points for visitors to get out and experience the landscape. Numerous hiking trails along the way, most of which are day hikes, lead to scenic lookouts over surrounding glaciers or lakes.', 'https://www.planetware.com/wpimages/2021/07/canada-banff-national-park-attractions-things-to-do-icefields-parkway-bow-lake.jpg', '-118.0529505', '52.8190712'),

(3, 1, 'Moraine Lake', 'Moraine Lake in the Valley of the Ten Peaks. Like Lake Louise, this is another scenic setting with similar turquoise water and snow-capped peaks. It was for many years the location of the image on the reverse side of the old Canadian twenty dollar bill and is one of the most popular places to photograph in Canada.', 'https://www.planetware.com/photos-large/CDN/canada-banff-morraine-lake-2.jpg', '-116.1859853085267', '51.3215664'),

(3, 1, 'Waterton Lakes National Park', 'The Waterton-Glacier International Peace Park in the Rocky Mountains straddles the border between Alberta and the U.S. state of Montana. On the Canadian side of the border is Waterton Lakes National Park, while on the American side is Glacier National Park.', 'https://www.planetware.com/photos-large/CDN/alberta-waterton-lakes-national-park.jpg', '-113.98100763190487', '49.101117349999996'),

-- QUE
(4, 2, 'The Canadian Museum of History', 'the countrys oldest museums, dating back to 1856. It also happens to be the most-visited in Canada, with 1.2 million annual visitors. So why do so many people stop by? The Gatineau museums four million items trace the history of Canada, and the world, starting 20,000 years ago. In the Grand Hall, discover the story, culture and beliefs of Canadas Pacific First Nations, in a beautiful setting overlooking the Ottawa River and Parliament Hill. ', 'https://d3d0lqu00lnqvz.cloudfront.net/media/media/0773437a-aa96-4c83-91a9-7490cb4a4fd7.jpg', '-75.70857565213802', '45.4298332'),

(4, 2, 'The Montreal Botanical Garden', 'The expression stop and smell the flowers takes on a whole new meaning , one of the greatest in the world. With 22,000 plant species and cultivars living in its 10 greenhouses, 20 thematic gardens and a pavilion, you might have a tough time smelling them all, but why not dream big. Whether youre into lilacs, lotus flowers, orchids or succulents, or you just like looking at pretty flowers, theres a little something for everyone. An oasis within the city, only a few minutes from downtown. Its actually right beside the Olympic Stadium and Biodome, making for a great day trip.', 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/04/ba/12/5d/montreal-botanical-gardens.jpg?w=1200&h=-1&s=1', '-73.56126486604046', '45.5595147'),

(4, 2, 'Montmorency Falls Park', 'Many people are surprised to discover that a waterfall one and a half times higher than Niagara Falls sits just minutes from Quebec City. At 83m, the Montmorency Falls are a sight to behold, both from within the city and up close and personal in the Montmorency Falls Park (Parc de la Chute-Montmorency in French). Hang out near the base and feel the mist on your face, or ride the gondola up to the top for a spectacular view. More adventurous visitors might choose to hike one of the three Via Ferrata trails, stopping at viewpoints along the way for some Instagram-worthy shots, or even zip line across the falls. Of course, once you reach the top you can sit back and enjoy a great meal or a few celebratory drinks at the elegant Manoir Montmorency', 'https://images.squarespace-cdn.com/content/v1/591675241b10e3f7ad138acf/1500863785177-LVLD29MVYZ8B0Z9T1Y6K/Montmorency+Falls+from+Distance', '-71.1475263', '46.8905531'),

(4, 2, 'Place Royale', 'Place Royale is the birthplace of Québec City, where Samuel de Champlain established the first habitation in 1608 and where there remains an outstanding collection of 17th- and 18th-century buildings that are a small sampling of Old Québec. The pretty stone church Notre-Dame des Victoires, dating to 1688, faces the square, along with modern tourist attractions like an outpost of the Musée de la Civilisation.', 'https://www.planetware.com/photos-large/CDN/canada-quebec-city-place-royale.jpg', '-73.55430308501505', '45.50322845'),

(4, 2, 'Mont Tremblant', 'Ski resorts in the Canadian Laurentians are favorite winter destinations, and chief among them is Mont Tremblant - the highest peak in the Laurentians (960 meters), located about 150 kilometers north of Montréal. Good dining, entertainment, and ample accommodations define the resort community, which is housed in a quaint pedestrian village. The region is also a fall destination, when leaves turn autumn shades of orange, red, and gold.', 'https://officialmonttremblant.com/wp-content/uploads/2022/09/mont-tremblant-1.jpg', '-74.5891426', '46.11588'),

-- TORONTO
(5, 2, 'Mogouyan Hand-Pulled Noodles', 'Mogouyan first opened in 2019, bringing authentic Chinese cuisine to the city and serving bowls and bowls of its mouthwatering beef noodles. Its menu features an assortment of appetizers and grilled skewer variations, including 12 different noodle bowls to choose from.', 'https://images.dailyhive.com/20220704112925/Mogouyan-Hand-Pulled-Noodles.jpg', '-79.3866313', '43.6694587'),

(5, 2, 'Bar St. Lo', 'Torontos St Lawrence district is not only known for its historical past and iconic market, its also home to a rustic and intimate dining destination thats worth a visit.
Its design features heavy stone and wood accents from its exterior to its interior, offering a more laidback yet mysterious atmosphere. As for its menu, Bar St. Lo serves modern Canadian cuisine that is worth sharing with whoever is at your table. Pro tip: order a couple of its popular items to share.
', 'https://images.dailyhive.com/20220704055937/interior.jpg', '-79.39763935428266', '43.7015074'),

(5, 2, 'Pennys Hot Chicken', 'Toronto cant get enough hot fried chicken spots, and this new addition is nothing to joke about. Get ready for some hot and steamin eats. Pennys Hot Chicken has opened at 372 Yonge Street, offering Nashville-inspired fried chicken thats sure to heat up your summer foodie plans. From Plain Jane to No Georgie, Pennys has a seven-tier heat meter so customers can decide how hot they want their chicken.', 'https://images.dailyhive.com/20220629095831/fried-chicken.jpg', '-79.38079276646786', '43.6541457'),

(5, 2, ' SHINYI Handmade Dumplings', 'Theres an exciting Asian eatery hidden in plain sight on one of Torontos busiest streets and it serves the most colourful dumplings around. SHINYI Handmade Dumplings can be found at 641 Yonge Street and is known for its handmade dumplings, dim sum and more, made fresh every day. Dumplings are even made by the store window for passersbys to check out what they have in store. This spot ensures that its cuisine stays true to its authentic Chinese flavour. The team is passionate about every dish on the menu which is proven with every plate served.', 'https://images.dailyhive.com/20220713120438/shinyi-entry.jpg', '-79.3855938', '43.6677913'),

(5, 2, 'Capis', '1962 Capis pizzas has been feeding the families of Etobicoke. Now we are taking it back to the roots, way back to Italy. A passion for food and family, thats what started Capis and thats where we circle back to today.', 'https://images.pexels.com/photos/1566837/pexels-photo-1566837.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '-79.5127261', '43.6597964'),

-- NF
(6, 2, 'Entire bungalow', 'My property is not a new modern luxury home, it is a very comfy, cozy and homey cottage feel house. Perfect location, very close to all attractions (all main attractions within 10-20 mins walk), its located in a very quiet neighborhood.  My property provides free WIFI, free stream TV and free Netflix. The main theme of my house is: families, friends can relax and bond in the sunroom, porch and sunny private deck. Kids can play in the games room. Just leave your cars and walk to the Falls.', 'https://a0.muscache.com/im/pictures/170f6c0a-5a92-40ca-bdd6-c693d9a3082a.jpg?im_w=1200', '-79.1056998', '43.0812918'),

(6, 2, 'Rustic Modern home steps', 'Welcome to our home, the perfect spot between Niagara Falls and Niagara-on-the-Lake, and just minutes from all the Casinos, entertainment and attractions Niagara region has to offer. This Airbnb is fully equipped with the basic household essentials, ready for you to enjoy the entire home.
Close to nearby attractions:
Niagara Falls (2.0 km) 30 minute walk
Niagara Whirlpool (1.5 km) 15 minute walk
Historic Niagara-on-The-Lake (14 km) 25 minute drive', 'https://a0.muscache.com/im/pictures/miso/Hosting-671821391261354242/original/fd1d7bf7-203f-40ec-aa05-95a2da05dae7.jpeg?im_w=1200', '-79.5403113', '43.040265'),

(6, 2, 'Charming Carriage House in Niagaras Wine Country', 'A converted carriage house and former blacksmith shop with a rich history dating back to the 1800s - fully updated with brand new modern amenities. This is a one level plus loft bedroom, ideal for those who have challenges with stairs. Centrally located near the Falls, Niagara Parkway, Niagara-on-the-Lake, casinos, wineries and the largest outlet mall in Canada. A great gathering spot in any season with a full kitchen, laundry and outdoor space ready to entertain family and friends.', 'https://a0.muscache.com/im/pictures/b666d8c6-c955-418e-bb48-89d0b86ec467.jpg?im_w=720', '-79.0836614', '43.0669342'),

(6, 2, 'Cabin Rental', 'Lighthouse Landing is a cozy cottage rental located in Port Maitland, Ontario (10 minutes from Dunnville, ON).
This gorgeous home has south facing panoramic lakefront views that transcend calmness and relaxation. During your stay, you will have access to our private beach and entire home that all guests can enjoy.', 'https://a0.muscache.com/im/pictures/miso/Hosting-628147560679285718/original/d26e30c4-f283-46b4-a70b-145933fc1ce0.jpeg?im_w=1200', '-79.6188457', '42.9059168'),

(6, 2, 'Luxury Romantic Glamping Dome', 'Youll love this unique and romantic escape for 2, located 30 minutes from Niagara Falls in Port Colborne.
Our 400 sq ft geodome offers all the amenities needed for a relaxing, romantic getaway. Panoramic floor to ceiling window over looking a private pond with the opportunity to see wildlife from the comfort of inside the dome.
Enjoy a fireplace, hot tub, comfy queen size bed, private deck with a fire table, outdoor shower, firepit on your own island, incinerating indoor toilet, AC, and wifi.', 'https://a0.muscache.com/im/pictures/miso/Hosting-640956956932882729/original/218fa3c3-60ac-4249-b502-70d371e5370b.jpeg?im_w=1200', '-79.2513905', '42.8862392');
